# Site settings
title: "Mesurer la diversité des femmes LGBT dans la tech" 
email: hello@lwtparis.fr
url: https://lwt-index.fr
description: "Projet collaboratif de Lesbians Who Tech Paris visant à mesurer collectivement comment améliorer la visibilité des lesbiennes et personnes LGBT dans la tech en France. "
skills: "Observatoire de la visibilité"
meta_author: Lesbians Who Tech Paris 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EEEEEE #d8b365
  primary-rgb: "39, 196, 244" #"216,179,101"
  secondary: 0A070C #B2230B
  secondary-dark: 26BDEA #F62459 #01665e

# Footer settings
footer:
  copyright: CC-BY
  location: Location
  social: Contact
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/LwTechParis
  - title: mail
    url: mailto:hello@lwtparis.fr


# Postal address (add as many lines as necessary)
address:
  - line: LWT Paris Summit
  - line: Paris

# Credits content
credits: 'Lesbians Who Tech Paris'

# Build settings
markdown: kramdown
permalink: pretty
